version: '3.8'
services:
  db:
    image: postgres:16
    container_name: my_news_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
