export const FLAG: unique symbol = Symbol('FLAG');
type FEED_INFO_FLAG = typeof FLAG;

export type FeedInfo = {
  label: string;
  url: string;
  flags?: FEED_INFO_FLAG[];
};

const createFeedList = (feedInfoTuples: [label: string, url: string, flags?: FEED_INFO_FLAG[]][]) => {
  const feedInfoList: FeedInfo[] = [];

  for (const [label, url, flags] of feedInfoTuples) {
    feedInfoList.push({ label, url, flags });
  }

  return feedInfoList;
};

// フィード一覧
export const feedList: FeedInfo[] = createFeedList([
  // ['企業名など', 'URL'],
  ['10ANTZ', 'https://developers.10antz.co.jp/feed'],
  ['10X', 'https://product.10x.co.jp/feed'],
  ['ANDPAD', 'https://tech.andpad.co.jp/feed'],
  ['ARIGATOBANK', 'https://medium.com/feed/arigatobank-tech-blog'],
  ['AppBrew', 'https://tech.appbrew.io/feed'],
  ['BASE', 'https://devblog.thebase.in/feed'],
  ['CAMPFIRE', 'https://note.com/campfire_dev/rss'],
  ['CARTA', 'https://techblog.cartaholdings.co.jp/feed'],
  ['CROOZ', 'https://croozblog.hatenablog.com/feed'],
  ['CULTA', 'https://techblog.culta.jp/feed'],
  ['Chatwork', 'https://creators-note.chatwork.com/feed'],
  ['Classi', 'https://tech.classi.jp/feed'],
  ['CryptoGames', 'https://zenn.dev/p/cryptogames/feed', [FLAG]],
  ['CyberZ', 'https://note.com/cyberz_cto/rss'],
  ['DeNA SWET', 'https://swet.dena.com/feed'],
  ['DeNA', 'https://engineering.dena.com/blog/index.xml'],
  ['DeNA', 'https://zenn.dev/p/dena/feed', [FLAG]],
  ['FiNC', 'https://medium.com/feed/finc-engineering'],
  ['Filot', 'https://filot-nextd2.hatenablog.com/feed'],
  ['Findy', 'https://tech.findy.co.jp/feed'],
  ['GMOアドパートナーズ', 'https://techblog.gmo-ap.jp/feed/'],
  ['GMOインターネット', 'https://developers.gmo.jp/feed/'],
  ['GMOグループ研究開発本部', 'https://recruit.gmo.jp/engineer/jisedai/blog/feed/'],
  ['GMOグローバルサイン・ホールディングス', 'https://tech.gmogshd.com/feed/'],
  ['GMOペパボ', 'https://tech.pepabo.com/feed.xml'],
  ['GMOリサーチ', 'https://gmor-sys.com/feed/'],
  ['GREE', 'https://labs.gree.jp/blog/feed/'],
  ['GiftX', 'https://zenn.dev/p/giftx_blog/feed', [FLAG]],
  ['Goodpatch', 'https://goodpatch-tech.hatenablog.com/feed'],
  ['Google Cloud Japan', 'https://zenn.dev/p/google_cloud_jp/feed', [FLAG]],
  ['Google', 'https://developers-jp.googleblog.com/atom.xml'],
  ['GreenSnap', 'https://greensnap-tech.hatenablog.com/feed'],
  ['Grooves', 'https://tech.grooves.com/feed'],
  ['Gunosy', 'https://tech.gunosy.io/feed'],
  ['Gunosyデータ分析', 'https://data.gunosy.io/feed'],
  ['HERP', 'https://tech-hub.herp.co.jp/feed.xml'],
  ['HRBrain', 'https://times.hrbrain.co.jp/feed'],
  ['HRBrain', 'https://zenn.dev/p/hrbrain/feed', [FLAG]],
  ['IVRy', 'https://zenn.dev/p/ivry/feed', [FLAG]],
  ['KARAKURI', 'https://medium.com/feed/karakuri'],
  ['LAPRAS', 'https://ai-lab.lapras.com/feed/'],
  ['LINEヤフー', 'https://techblog.lycorp.co.jp/ja/feed/index.xml'],
  ['LayerX', 'https://tech.layerx.co.jp/feed'],
  ['LayerX', 'https://zenn.dev/p/layerx/feed', [FLAG]],
  ['Legoliss', 'https://blog.legoliss.co.jp/feed'],
  ['Luup', 'https://zenn.dev/luup/feed'],
  ['M&Aクラウド', 'https://tech.macloud.jp/feed'],
  ['MIXI', 'https://zenn.dev/p/mixi/feed', [FLAG]],
  ['Makuake', 'https://note.com/dev_makuake/rss'],
  ['MicroAd', 'https://developers.microad.co.jp/feed'],
  ['Money Forward Kessai', 'https://tech.mfkessai.co.jp/index.xml'],
  ['NTTコミュニケーションズ', 'https://engineers.ntt.com/feed'],
  ['NTTソフトウェアイノベーションセンタ ', 'https://medium.com/feed/nttlabs'],
  ['Offers', 'https://zenn.dev/offers/feed'],
  ['Offers', 'https://zenn.dev/p/overflow_offers/feed', [FLAG]],
  ['OpenWork', 'https://techblog.openwork.co.jp/feed'],
  ['PR TIMES', 'https://developers.prtimes.jp/feed/'],
  ['Playground', 'https://tech.playground.style/feed/'],
  ['Qiita', 'https://zine.qiita.com/feed/'],
  ['Retty', 'https://engineer.retty.me/feed'],
  ['SEGA', 'https://techblog.sega.jp/feed'],
  ['SHIFT Group', 'https://note.com/shift_tech/rss'],
  ['SHOWROOM', 'https://note.com/showroom_blog/rss'],
  ['SQUARE ENIX', 'https://blog.jp.square-enix.com/iteng-blog/index.xml'],
  ['Salesforce', 'https://developer.salesforce.com/jpblogs/feed/'],
  ['Sansan', 'https://buildersbox.corp-sansan.com/feed'],
  ['Seeed', 'https://lab.seeed.co.jp/feed'],
  ['SmartBank', 'https://blog.smartbank.co.jp/feed'],
  ['SmartHR', 'https://tech.smarthr.jp/feed'],
  ['SmartNews', 'https://developer.smartnews.com/blog/feed'],
  ['SmartNewsメディア担当チーム', 'https://www.mediatechnology.jp/feed'],
  ['Speee', 'https://tech.speee.jp/feed'],
  ['Studyplus', 'https://tech.studyplus.co.jp/feed'],
  ['TVer Technologies', 'https://techblog.tver-tech.co.jp/feed'],
  ['TVer', 'https://techblog.tver.co.jp/feed'],
  ['Ubie', 'https://zenn.dev/p/ubie_dev/feed', [FLAG]],
  ['Unipos', 'https://fringeneer.hatenablog.com/feed'],
  ['Uzabase', 'https://tech.uzabase.com/feed'],
  ['Voicy', 'https://medium.com/feed/voicy-engineering'],
  ['Voicy', 'https://zenn.dev/p/voicy/feed', [FLAG]],
  ['Wiz', 'https://tech.012grp.co.jp/feed'],
  ['YOUTRUST', 'https://tech.youtrust.co.jp/feed'],
  ['ZOZO', 'https://techblog.zozo.com/feed'],
  ['ZOZO', 'https://zenn.dev/p/zozotech/feed', [FLAG]],
  ['Zenn', 'https://zenn.dev/p/team_zenn/feed', [FLAG]],
  ['atama plus', 'https://zenn.dev/atamaplus_dev/feed'],
  ['dip', 'https://developer.dip-net.co.jp/feed'],
  ['for Startups', 'https://tech.forstartups.com/feed'],
  ['freee', 'https://developers.freee.co.jp/feed'],
  ['hacomono', 'https://techblog.hacomono.jp/feed'],
  ['note', 'https://engineerteam.note.jp/m/m70da42dac8cf/rss'],
  ['paiza', 'https://paiza.hatenablog.com/feed'],
  ['pixiv', 'https://zenn.dev/p/pixiv/feed', [FLAG]],
  ['stand.fm', 'https://note.com/standfm_company/rss'],
  ['vivit', 'https://vivit.hatenablog.com/feed'],
  ['くらしのマーケット', 'https://tech.curama.jp/feed'],
  ['ぐるなび', 'https://developers.gnavi.co.jp/feed'],
  ['じげん', 'https://overs.zigexn.co.jp/technology/feed/'],
  ['はてな', 'https://developer.hatenastaff.com/feed'],
  ['みてね', 'https://team-blog.mitene.us/feed'],
  ['ゆめみ', 'https://zenn.dev/p/yumemi_inc/feed'],
  ['アカツキ', 'https://hackerslab.aktsk.jp/feed'],
  ['アソビュー', 'https://tech.asoview.co.jp/feed'],
  ['アトラエ', 'https://atraetech.hatenablog.com/feed'],
  ['ウィルゲート', 'https://tech.willgate.co.jp/feed'],
  ['エムスリー', 'https://www.m3tech.blog/feed'],
  ['カカクコム', 'https://kakaku-techblog.com/feed'],
  ['カケハシ', 'https://kakehashi-dev.hatenablog.com/feed'],
  ['カミナシ', 'https://kaminashi-developer.hatenablog.jp/feed'],
  ['カヤック', 'https://techblog.kayac.com/feed'],
  ['ガイアックス', 'https://gaiax.hatenablog.com/feed'],
  ['キカガク', 'https://www.kikagaku.co.jp/kikagaku-blog/feed/'],
  ['クイック', 'https://aimstogeek.hatenablog.com/feed'],
  ['クイックガード', 'https://tech.quickguard.jp/index.xml'],
  ['クックパッド', 'https://techlife.cookpad.com/feed'],
  ['クラウドワークス', 'https://engineer.crowdworks.jp/feed'],
  ['クラシコム', 'https://note.com/kurashicom_tech/rss'],
  ['クロスマート', 'https://xmart-techblog.hatenablog.com/feed'],
  ['コインチェック', 'https://tech.coincheck.blog/feed'],
  ['ココナラ', 'https://zenn.dev/coconala/feed'],
  ['コドモン', 'https://tech.codmon.com/feed'],
  ['コネヒト', 'https://tech.connehito.com/feed'],
  ['コミューン', 'https://tech.commmune.jp/feed'],
  ['サイオステクノロジー', 'https://tech-lab.sios.jp/feed'],
  ['サイバーエージェント', 'https://developers.cyberagent.co.jp/blog/feed/'],
  ['サイボウズ Necoチーム', 'https://zenn.dev/p/cybozu_neco/feed', [FLAG]],
  ['サイボウズ データチーム', 'https://zenn.dev/p/cybozu_data/feed', [FLAG]],
  ['サイボウズ フロントエンド', 'https://zenn.dev/p/cybozu_frontend/feed', [FLAG]],
  ['サイボウズ 生産性向上チーム', 'https://zenn.dev/p/cybozu_ept/feed', [FLAG]],
  ['サイボウズ', 'https://blog.cybozu.io/feed'],
  ['サムザップ', 'https://tech.sumzap.co.jp/feed'],
  ['シェアフル', 'https://zenn.dev/sharefull/feed'],
  ['ジェイテックジャパン', 'https://zenn.dev/jtechjapan/feed'],
  ['ジモティー', 'https://jmty-tech.hatenablog.com/feed'],
  ['スタディサプリ', 'https://blog.studysapuri.jp/feed'],
  ['ストックマーク', 'https://tech.stockmark.co.jp/index.xml'],
  ['タイミー', 'https://tech.timee.co.jp/feed'],
  ['テックタッチ', 'https://techtouch.hatenablog.jp/feed'],
  ['テックファーム', 'https://www.techfirm.co.jp/blog/?feed=rss2'],
  ['テラーノベル', 'https://zenn.dev/p/tellernovel_inc/feed', [FLAG]],
  ['チームラボ　フロントエンド班', 'https://zenn.dev/p/teamlab_fe/feed', [FLAG]],
  ['ドワンゴ', 'https://dwango.github.io/index.xml'],
  ['ドワンゴ教育サービス', 'https://blog.nnn.dev/feed'],
  ['ヌーラボ', 'https://nulab.com/ja/blog/categories/techblog/feed/'],
  ['ネクストビート', 'https://medium.com/feed/nextbeat-engineering'],
  ['ハコベル', 'https://zenn.dev/p/hacobell_dev/feed', [FLAG]],
  ['パーソルキャリア', 'https://techtekt.persol-career.co.jp/feed'],
  ['パーソルプロセス＆テクノロジー', 'https://note.com/ppt_hr/m/md77242321979/rss'],
  ['ビザスク', 'https://tech.visasq.com/feed'],
  ['ビザスク', 'https://zenn.dev/p/visasq/feed', [FLAG]],
  ['ピクシブ', 'https://inside.pixiv.blog/feed'],
  ['フクロウラボ', 'https://developers.fukurou-labo.co.jp/feed/'],
  ['マイベスト', 'https://zenn.dev/mybest/feed'],
  ['マネーフォワード ', 'https://moneyforward-dev.jp/feed'],
  ['ミクシィ', 'https://mixi-developers.mixi.co.jp/feed'],
  ['メルカリ', 'https://engineering.mercari.com/blog/feed.xml'],
  ['モノタロウ', 'https://tech-blog.monotaro.com/feed'],
  ['ラクス', 'https://tech-blog.rakus.co.jp/feed'],
  ['ラクスフロントエンドチーム', 'https://note.com/rakus_fe/m/m653605948abe/rss'],
  ['ラクスル', 'https://techblog.raksul.com/feed'],
  ['ランサーズ', 'https://engineer.blog.lancers.jp/feed/'],
  ['リンクアンドモチベーション', 'https://link-and-motivation.hatenablog.com/feed'],
  ['リンコード', 'https://blog.linkode.co.jp/feed'],
  ['レアジョブ', 'https://rarejob-tech-dept.hatenablog.com/feed'],
  ['レコチョク', 'https://techblog.recochoku.jp/feed/atom'],
  ['レバテック', 'https://zenn.dev/p/levtech/feed', [FLAG]],
  ['レバレジーズ', 'https://tech.leverages.jp/feed'],
  ['ログラス', 'https://zenn.dev/p/loglass/feed', [FLAG]],
  ['ワンキャリア', 'https://note.com/dev_onecareer/rss'],
  ['一休', 'https://user-first.ikyu.co.jp/feed'],
  ['弁護士ドットコム', 'https://creators.bengo4.com/feed'],
  ['弥生', 'https://tech-blog.yayoi-kk.co.jp/feed'],
  ['楽天コマース', encodeURI('https://commerce-engineer.rakuten.careers/feed/category/テック')],
  ['永和システムマネジメント', 'https://blog.agile.esm.co.jp/feed'],
  ['電通国際情報サービス', 'https://tech.dentsusoken.com/feed'],
  ['食べチョク', 'https://tech.tabechoku.com/feed'],
  ['食べログ', 'https://tech-blog.tabelog.com/feed'],
]);